#SPDX-License-Identifier: MIT
galaxy_info:
  author: Harish N Shetty
  description: Ansible role for nginx
  # company: your company (optional)

  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: "2.20"

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - nginx
    - system

dependencies: []
