#SPDX-License-Identifier: MIT-0
---
# tasks/main.yml — ansible

- name: Install ansible
  apt:
    name: ansible
    state: present
    update_cache: yes

- name: Enable ansible on boot
  service:
    name: ansible
    enabled: yes

