#SPDX-License-Identifier: MIT-0
---
# tasks/main.yml — git

- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Enable git on boot
  service:
    name: git
    enabled: yes

